In [ ]:
# correct the docstrings

def calculate(value1,value2):
# calculates the sum of two numbers and multiplies the sum by its product
    return (value1+value2)*value1*value2

print(calculate(10,5))

750


In [ ]:
calculate.__doc__

In [ ]:
# convert list of ids to primary keys
# Primary keys are unique values

list1 =[1,1,2,34,2,1,3,5,6,8,9]

In [ ]:
print(set(list1))

{1, 2, 3, 34, 5, 6, 8, 9}


In [ ]:
# whats wrong with the print output
Gender = 'Male'
Age = '33.133'
DOB = '23/04/1998.45'
store_str = 'I am a {1} YO {2} and my date of bith is {0}'.format(DOB[:-3],int(float(Age)),Gender)
print(store_str)


# index of variables is not in correct order in format method, nor is the index specified, to fix I will enter correct index and get rid of decimals.

I am a 33 YO Male and my date of bith is 23/04/1998


In [ ]:
# Write a Python program to create a list by concatenating a given list which range goes from 1 to n
# example list ['a','b']
# n = 5
# output ['a1','a2','a3','a4','a5','b1','b2','b3','b4','b5']



In [5]:
n = int(input())
list = ['a', 'b']
nlist = ["{}{}".format(x, y) for y in range(1, n+1) for x in list]

print(nlist)

5
['a1', 'b1', 'a2', 'b2', 'a3', 'b3', 'a4', 'b4', 'a5', 'b5']


In [ ]:
#Whats wrong with the syntax
def number_info(value):
  if value == 2:
    return 'Value is 2'
  elif value%2==0:
    return 'Value is prime'
  elif value<5:
    return 'Value is less than 5'

# prime numbers are numbers divisable by 1 and the number itself, the first elif is wrong 
# and the function doesnt account for odd values 5 and above, change all to if.

In [ ]:
#Whats wrong with the syntax
x = int(input('Enter an integer number: ' ))

def number_info(n):
    for i in range(2,n):
        if (n%i) == 0:
            return 'Value is not prime'         
    return 'Value is prime'

   

        
print(number_info(x))


Enter an integer number: 4
Value is not prime


In [ ]:
#Write a function to return every nth element from the list and store it in a single list as a list with nested list each containing n elements
# example:
# [1,2,3,4,5,6,7,8,8,9]
# n=3
# output:
# [[1,2,3],[4,5,6],[7,8,8],[9]]

import numpy as np

arr = np.random.randint(0,100,34)


In [ ]:
a=[]

for i in range(0,len(arr),3):
    #print(i)
    a.append(arr[i:i+3])

In [ ]:
arr

array([21, 97, 49, 60, 30, 44, 69, 66, 28, 56, 63, 89, 87, 26, 71, 93, 92,
       92,  3, 52, 99, 19, 72, 79,  2, 73,  1, 48, 82, 16, 31, 92, 66, 70])

In [ ]:
a

[array([21, 97, 49]),
 array([60, 30, 44]),
 array([69, 66, 28]),
 array([56, 63, 89]),
 array([87, 26, 71]),
 array([93, 92, 92]),
 array([ 3, 52, 99]),
 array([19, 72, 79]),
 array([ 2, 73,  1]),
 array([48, 82, 16]),
 array([31, 92, 66]),
 array([70])]