In [ ]:
#Given a 1D array, negate all elements which are between 3 and 8, in place.


In [3]:
import numpy as np

In [13]:
a = np.random.random(12)
a


array([0.24907349, 0.83518096, 0.37694518, 0.35034211, 0.06204109,
       0.36927201, 0.21742334, 0.04419124, 0.53925141, 0.8432456 ,
       0.31031237, 0.86441803])

In [15]:
a[(a>=3)&(a<=8)]*=-1
a

array([0.24907349, 0.83518096, 0.37694518, 0.35034211, 0.06204109,
       0.36927201, 0.21742334, 0.04419124, 0.53925141, 0.8432456 ,
       0.31031237, 0.86441803])

In [18]:
x=5
x*=-1   # multiplies x by -1
x

-5

In [19]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
b = np.random.uniform(5,10,(5, 3))
b

array([[8.49739781, 5.61054041, 7.15303453],
       [6.14667221, 9.47595476, 6.49705965],
       [9.6439709 , 5.18446313, 5.19332024],
       [5.26061353, 5.4110364 , 7.12083455],
       [9.55335313, 8.33479917, 6.54780305]])

In [ ]:
# Given a 1D array, add 1 to every alternate element.
a
a[::2]=a[::2]+1
a

array([1.76286615, 0.53281217, 1.36405572, 0.41126815, 1.24624624,
       0.11203632, 1.21297768, 0.69958934, 1.92405496, 0.89076414,
       1.35501525, 0.82317797])

In [ ]:
a[::2]+=1
a

array([1.38149612, 0.03400909, 1.88722056, 0.4971579 , 1.02616028,
       0.8918212 , 1.99259084, 0.28025065, 1.44650545, 0.85163306,
       1.47433037, 0.27746328])

In [ ]:
# Given a 2D array, flatten it to a 1D array.
c = b.flatten()
c

array([7.94287301, 6.9439076 , 7.25474753, 6.23460529, 7.89789449,
       9.77940341, 7.97220031, 6.42526957, 5.37384608, 7.81189703,
       5.93871838, 7.86557354, 5.67732528, 6.87813835, 6.65005571])

In [ ]:
# Convert a 1D array of 20 grayscale image values into a 2D array of 5x4 shape.


In [20]:
a = np.arange(20)
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
# replace odd numbers in a 3 dimensional array with even number

import numpy as np
np.random.seed(100)
store = np.random.normal(5,10,27).astype(int)


In [22]:
store=store.reshape((3,3,3))

In [23]:
store

array([[[-12,   8,  16],
        [  2,  14,  10],
        [  7,  -5,   3]],

       [[  7,   0,   9],
        [  0,  13,  11],
        [  3,   0,  15]],

       [[  0,  -6,  21],
        [ 20,   2,  -3],
        [  6,  14,  12]]])

In [26]:
store[store%2!=0]+=1
store

array([[[-12,   8,  16],
        [  2,  14,  10],
        [  8,  -4,   4]],

       [[  8,   0,  10],
        [  0,  14,  12],
        [  4,   0,  16]],

       [[  0,  -6,  22],
        [ 20,   2,  -2],
        [  6,  14,  12]]])

In [ ]:
#Exercise 2 create a 2 dimension numpy array to fill with 0's and 1's but the output should look like a checker board
'''
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
'''




In [88]:
# Solution
z = np.zeros((8,8), dtype=int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [89]:
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [94]:
#Exercise 3 Consider a numpy array of shape (200,3)
# We need to extract those rows which are symmetrical.
# [1,2,1] is symmetrical [1,2,3] isnt

Z = np.random.randint(0,5,(200,3))
# [0,2,0]
# solution 1
Z

array([[0, 4, 2],
       [0, 3, 1],
       [1, 1, 0],
       [0, 1, 3],
       [4, 3, 2],
       [2, 2, 0],
       [3, 2, 3],
       [0, 4, 2],
       [3, 1, 3],
       [1, 1, 1],
       [0, 2, 4],
       [2, 0, 4],
       [3, 2, 4],
       [1, 2, 0],
       [0, 4, 4],
       [1, 1, 2],
       [0, 1, 0],
       [2, 2, 4],
       [2, 2, 3],
       [2, 1, 4],
       [1, 3, 2],
       [3, 3, 4],
       [2, 4, 2],
       [3, 1, 0],
       [4, 2, 0],
       [2, 3, 2],
       [1, 0, 0],
       [2, 2, 1],
       [3, 2, 3],
       [1, 0, 1],
       [0, 3, 0],
       [2, 1, 3],
       [1, 4, 3],
       [1, 3, 0],
       [0, 0, 0],
       [0, 0, 3],
       [0, 0, 1],
       [1, 1, 2],
       [0, 4, 4],
       [4, 4, 3],
       [0, 4, 3],
       [1, 1, 2],
       [3, 1, 3],
       [1, 3, 1],
       [4, 0, 0],
       [2, 0, 0],
       [1, 4, 3],
       [1, 0, 4],
       [1, 2, 2],
       [2, 4, 0],
       [3, 2, 4],
       [4, 2, 1],
       [4, 3, 2],
       [4, 3, 0],
       [0, 3, 0],
       [3,

In [95]:
#Solution
Z[:,0]

array([0, 0, 1, 0, 4, 2, 3, 0, 3, 1, 0, 2, 3, 1, 0, 1, 0, 2, 2, 2, 1, 3,
       2, 3, 4, 2, 1, 2, 3, 1, 0, 2, 1, 1, 0, 0, 0, 1, 0, 4, 0, 1, 3, 1,
       4, 2, 1, 1, 1, 2, 3, 4, 4, 4, 0, 3, 0, 2, 2, 2, 2, 2, 2, 0, 3, 0,
       1, 2, 2, 4, 3, 3, 1, 4, 0, 1, 2, 3, 1, 1, 1, 3, 0, 2, 4, 2, 1, 4,
       0, 0, 4, 4, 0, 1, 3, 1, 1, 1, 0, 1, 1, 1, 2, 3, 3, 3, 0, 1, 2, 1,
       4, 0, 2, 1, 3, 4, 2, 1, 2, 4, 3, 2, 2, 2, 3, 1, 0, 4, 0, 4, 2, 1,
       2, 4, 2, 1, 4, 2, 2, 3, 1, 0, 0, 1, 0, 0, 3, 4, 4, 3, 1, 1, 0, 0,
       3, 1, 3, 2, 1, 0, 3, 3, 3, 3, 0, 1, 3, 4, 0, 2, 4, 0, 4, 2, 2, 2,
       0, 3, 0, 2, 3, 3, 2, 1, 4, 1, 4, 0, 1, 0, 0, 0, 1, 2, 2, 4, 0, 3,
       4, 4])

In [96]:
Z[:,0]==Z[:,-1]


array([False, False, False, False, False, False,  True, False,  True,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False, False,  True, False,
       False,  True,  True,  True, False, False, False,  True, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False,  True, False, False,  True, False,  True,
       False,  True, False, False, False, False, False, False, False,
        True, False, False,  True, False, False, False, False, False,
        True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True,  True,
       False, False,

In [97]:
Z[Z[:,0]==Z[:,-1]]

array([[3, 2, 3],
       [3, 1, 3],
       [1, 1, 1],
       [0, 1, 0],
       [2, 4, 2],
       [2, 3, 2],
       [3, 2, 3],
       [1, 0, 1],
       [0, 3, 0],
       [0, 0, 0],
       [3, 1, 3],
       [1, 3, 1],
       [0, 3, 0],
       [0, 3, 0],
       [1, 0, 1],
       [4, 1, 4],
       [3, 2, 3],
       [4, 1, 4],
       [3, 4, 3],
       [4, 4, 4],
       [4, 2, 4],
       [3, 4, 3],
       [1, 2, 1],
       [2, 2, 2],
       [4, 2, 4],
       [3, 1, 3],
       [1, 4, 1],
       [0, 1, 0],
       [4, 0, 4],
       [1, 4, 1],
       [2, 3, 2],
       [3, 2, 3],
       [0, 2, 0],
       [2, 1, 2],
       [3, 0, 3],
       [1, 0, 1],
       [0, 1, 0],
       [4, 0, 4]])

In [ ]:
Z

array([[4, 0, 0],
       [1, 2, 1],
       [0, 3, 3],
       [4, 1, 2],
       [0, 3, 1],
       [4, 3, 2],
       [4, 3, 1],
       [0, 1, 4],
       [4, 0, 3],
       [3, 0, 1],
       [1, 4, 3],
       [1, 0, 1],
       [2, 1, 3],
       [4, 3, 4],
       [3, 3, 2],
       [4, 1, 2],
       [2, 1, 2],
       [0, 2, 4],
       [3, 2, 1],
       [3, 4, 2],
       [3, 2, 0],
       [1, 3, 0],
       [2, 2, 4],
       [4, 1, 1],
       [2, 3, 2],
       [4, 2, 4],
       [1, 4, 0],
       [1, 1, 4],
       [0, 1, 0],
       [4, 3, 2],
       [2, 3, 2],
       [3, 4, 3],
       [0, 1, 3],
       [2, 4, 3],
       [1, 0, 1],
       [3, 1, 2],
       [2, 2, 1],
       [2, 1, 0],
       [1, 0, 2],
       [1, 1, 2],
       [2, 0, 3],
       [3, 2, 4],
       [2, 0, 1],
       [3, 4, 2],
       [1, 4, 0],
       [4, 1, 3],
       [3, 0, 0],
       [0, 0, 4],
       [0, 1, 1],
       [3, 4, 3],
       [0, 0, 0],
       [3, 1, 2],
       [4, 1, 4],
       [1, 2, 4],
       [2, 3, 2],
       [2,

In [ ]:
# Exercise 4 Make the above array symmetrical


In [98]:
#Solution
Z[:,0]=Z[:,-1]
Z

array([[2, 4, 2],
       [1, 3, 1],
       [0, 1, 0],
       [3, 1, 3],
       [2, 3, 2],
       [0, 2, 0],
       [3, 2, 3],
       [2, 4, 2],
       [3, 1, 3],
       [1, 1, 1],
       [4, 2, 4],
       [4, 0, 4],
       [4, 2, 4],
       [0, 2, 0],
       [4, 4, 4],
       [2, 1, 2],
       [0, 1, 0],
       [4, 2, 4],
       [3, 2, 3],
       [4, 1, 4],
       [2, 3, 2],
       [4, 3, 4],
       [2, 4, 2],
       [0, 1, 0],
       [0, 2, 0],
       [2, 3, 2],
       [0, 0, 0],
       [1, 2, 1],
       [3, 2, 3],
       [1, 0, 1],
       [0, 3, 0],
       [3, 1, 3],
       [3, 4, 3],
       [0, 3, 0],
       [0, 0, 0],
       [3, 0, 3],
       [1, 0, 1],
       [2, 1, 2],
       [4, 4, 4],
       [3, 4, 3],
       [3, 4, 3],
       [2, 1, 2],
       [3, 1, 3],
       [1, 3, 1],
       [0, 0, 0],
       [0, 0, 0],
       [3, 4, 3],
       [4, 0, 4],
       [2, 2, 2],
       [0, 4, 0],
       [4, 2, 4],
       [1, 2, 1],
       [2, 3, 2],
       [0, 3, 0],
       [0, 3, 0],
       [0,