In [ ]:
#Given a 1D array, negate all elements which are between 3 and 8, in place.


In [ ]:
a = np.random.random(12)
a


array([0.38149612, 0.03400909, 0.88722056, 0.4971579 , 0.02616028,
       0.8918212 , 0.99259084, 0.28025065, 0.44650545, 0.85163306,
       0.47433037, 0.27746328])

In [ ]:
a[(a>=3)&(a<=8)]*=-1

In [ ]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
b = np.random.uniform(5,10,(5, 3))
b

array([[7.94287301, 6.9439076 , 7.25474753],
       [6.23460529, 7.89789449, 9.77940341],
       [7.97220031, 6.42526957, 5.37384608],
       [7.81189703, 5.93871838, 7.86557354],
       [5.67732528, 6.87813835, 6.65005571]])

In [ ]:
# Given a 1D array, add 1 to every alternate element.
a
a[::2]=a[::2]+1
a

array([1.76286615, 0.53281217, 1.36405572, 0.41126815, 1.24624624,
       0.11203632, 1.21297768, 0.69958934, 1.92405496, 0.89076414,
       1.35501525, 0.82317797])

In [ ]:
a[::2]+=1
a

array([1.38149612, 0.03400909, 1.88722056, 0.4971579 , 1.02616028,
       0.8918212 , 1.99259084, 0.28025065, 1.44650545, 0.85163306,
       1.47433037, 0.27746328])

In [ ]:
# Given a 2D array, flatten it to a 1D array.
c = b.flatten()
c

array([7.94287301, 6.9439076 , 7.25474753, 6.23460529, 7.89789449,
       9.77940341, 7.97220031, 6.42526957, 5.37384608, 7.81189703,
       5.93871838, 7.86557354, 5.67732528, 6.87813835, 6.65005571])

In [ ]:
# Convert a 1D array of 20 grayscale image values into a 2D array of 5x4 shape.


In [ ]:
# replace odd numbers in a 3 dimensional array with even number

import numpy as np
np.random.seed(100)
store = np.random.normal(5,10,27).astype(int)


In [ ]:
store=store.reshape((3,3,3))

In [ ]:
store

array([[[-12,   8,  16],
        [  2,  14,  10],
        [  7,  -5,   3]],

       [[  7,   0,   9],
        [  0,  13,  11],
        [  3,   0,  15]],

       [[  0,  -6,  21],
        [ 20,   2,  -3],
        [  6,  14,  12]]])

In [ ]:
#Exercise 2 create a 2 dimension numpy array to fill with 0's and 1's but the output should look like a checker board
'''
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
'''
# Solution



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Exercise 3 Consider a numpy array of shape (200,3)
# We need to extract those rows which are symmetrical.
# [1,2,1] is symmetrical [1,2,3] isnt

Z = np.random.randint(0,5,(200,3))
# [0,2,0]
# solution 1


In [111]:
Z

array([[4, 0, 0],
       [1, 2, 1],
       [0, 3, 3],
       [4, 1, 2],
       [0, 3, 1],
       [4, 3, 2],
       [4, 3, 1],
       [0, 1, 4],
       [4, 0, 3],
       [3, 0, 1],
       [1, 4, 3],
       [1, 0, 1],
       [2, 1, 3],
       [4, 3, 4],
       [3, 3, 2],
       [4, 1, 2],
       [2, 1, 2],
       [0, 2, 4],
       [3, 2, 1],
       [3, 4, 2],
       [3, 2, 0],
       [1, 3, 0],
       [2, 2, 4],
       [4, 1, 1],
       [2, 3, 2],
       [4, 2, 4],
       [1, 4, 0],
       [1, 1, 4],
       [0, 1, 0],
       [4, 3, 2],
       [2, 3, 2],
       [3, 4, 3],
       [0, 1, 3],
       [2, 4, 3],
       [1, 0, 1],
       [3, 1, 2],
       [2, 2, 1],
       [2, 1, 0],
       [1, 0, 2],
       [1, 1, 2],
       [2, 0, 3],
       [3, 2, 4],
       [2, 0, 1],
       [3, 4, 2],
       [1, 4, 0],
       [4, 1, 3],
       [3, 0, 0],
       [0, 0, 4],
       [0, 1, 1],
       [3, 4, 3],
       [0, 0, 0],
       [3, 1, 2],
       [4, 1, 4],
       [1, 2, 4],
       [2, 3, 2],
       [2,

In [ ]:
# Exercise 4 Make the above array symmetrical
